language: node_js
node_js:
  - "stable"
  - "iojs"
notifications:
  email:
  - mapopa@gmail.com  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq firebird2.5-superclassic 
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start
install:
#script: tap --gc test/js/*-test.js
